### ISSUE TITLE
Error: Cannot find module 'pngjs'

### ISSUE THREAD

**Issue by NardJ** [Photonsters/VoxelsOps#2]
I get an error when testing gyroid.js on a Linux Mint machine:
![image](https://user-images.githubusercontent.com/11459480/44741015-3277e980-aafc-11e8-9cf7-1b8a3b7ba0a6.png)

Am I doing something wrong? Is it a missing dependency?

**Comment by Antharon** [comment]
did you run 'npm install' first?

**Comment by Antharon** [comment]
I will clean up my packages soon and release new update, I abandoned my tries to releaseitas single build for each system, users will simply need to install node and electron to use that application.

**Comment by NardJ** [comment]
' npm install' did the trick. Should have read the readme better :-)
